version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - gateway-net
    depends_on:
      - certbot
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  certbot:
    image: certbot/certbot
    container_name: ${COMPOSE_PROJECT_NAME}-certbot
    volumes:
      - certbot_certs:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    # Команда запускает проверку на продление каждые 12 часов.
    # trap exit TERM; - корректно завершает работу при docker-compose down
    # wait $${!}; - ждет завершения sleep, не загружая CPU
    command: >
      sh -c "
        trap exit TERM;
        while :; do
          certbot renew --quiet;
          sleep 12h & wait $${!};
        done;
      "
    networks:
      - gateway-net

networks:
  gateway-net:
    name: ${WEB_GATEWAY_NETWORK}
    external: true

volumes:
  certbot_certs:
  certbot_www:
