version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-local-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - gateway-net
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  gateway-net:
    name: ${WEB_GATEWAY_NETWORK}
    external: true
